### ISSUE TITLE
Doesn't support ES 6 spread.

### ISSUE THREAD

**Issue by ErrorPro** [sindresorhus/gulp-jsvalidate#2]
https://github.com/facebook/esprima/issues/111

This plugin doesn't support es6 features. I think because of facebook is gonna deprecate esprima.

**Comment by sindresorhus** [comment]
This plugin uses normal Esprima.

https://github.com/jquery/esprima/tree/2.6

> Full support for ECMAScript 6 (ECMA-262)

If anything is missing, this is not the place to report.
